import 'package:flutter/material.dart';

List<Produtos> listaProdutos = [];

class Autogenerated {
  List<Produtos> produtos;

  Autogenerated({this.produtos});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    if (json['produtos'] != null) {
      produtos = new List<Produtos>();
      json['produtos'].forEach((v) {
        produtos.add(new Produtos.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.produtos != null) {
      data['produtos'] = this.produtos.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class Produtos {
  String nome;
  double preco;

  Produtos({this.nome, this.preco});

  Produtos.fromJson(Map<String, dynamic> json) {
    nome = json['nome'];
    preco = json['preco'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['nome'] = this.nome;
    data['preco'] = this.preco;
    return data;
  }
}

void inicializaUsuarios() {
  listaProdutos.clear();
}

Widget celulaUsuario(Produtos usuario, Function() onTap) {
  return GestureDetector(
    onTap: () {
      onTap();
    },
    child: Container(
      height: 60.0,
      child: Column(
        children: <Widget>[
          Text(
            usuario.nome,
            style: TextStyle(
              fontSize: 22.0,
              fontWeight: FontWeight.bold,
            ),
          ),
          Text(
            "RS ${usuario.preco}",
            style: TextStyle(
              color: Colors.red,
            ),
          ),
        ],
      ),
    ),
  );
}

List<Widget> listaWUsuario() {
  List<Widget> retorno = [];
  for (Produtos usuario in listaProdutos) {
    retorno.add(Container(
      height: 80.0,
      child: celulaUsuario(usuario, () {}),
    ));
  }
  return retorno;
}
